# Generated by Django 4.2.1 on 2025-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='incorrect_answers',
            field=models.IntegerField(default=0, verbose_name="Noto'g'ri javoblar soni"),
        ),
    ]
